name: Test 11.2 Custom Image 

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
        - arch: x86-64
          version: 11.2
        - arch: x86-64
          version: 12.2
        - arch: x86-64
          version: 12.4
        - arch: arm64
          version: 12.4
        - arch: x86-64
          version: 13.0
        - arch: arm64
          version: 13.0
        - arch: x86-64
          version: 13.1
        - arch: arm64
          version: 13.1
        - arch: x86-64
          version: 13.2
        - arch: arm64
          version: 13.2
        - arch: x86-64
          version: 13.3
        - arch: arm64
          version: 13.3
        - arch: x86-64
          version: 14.0
        - arch: arm64
          version: 14.0
        - arch: x86-64
          version: 14.1
        - arch: arm64
          version: 14.1
    steps:
    - uses: actions/checkout@v4
    - name: Test on ${{ matrix.os.version }}-${{ matrix.os.arch }}
      uses: cross-platform-actions/action@v0.23.0
      with:
        operating_system: freebsd
        architecture: ${{ matrix.os.arch }}
        version: ${{ matrix.os.version }}
        image_url: https://github.com/ophum/freebsd-builder/releases/download/untagged-d41abceab152472143b8/freebsd-${{ matrix.os.version }}-${{ matrix.os.arch }}.qcow2
        run: |
          uname -a

